
-- --------------------------------------------------------

--
-- Estructura de tabla para la tabla `home_banners`
--

CREATE TABLE `home_banners` (
  `id` int(11) NOT NULL,
  `url` text NOT NULL,
  `alt` varchar(200) NOT NULL,
  `target` varchar(50) NOT NULL,
  `pos` int(11) NOT NULL,
  `active` smallint(6) NOT NULL
) ENGINE=MyISAM DEFAULT CHARSET=latin1;

--
-- Volcado de datos para la tabla `home_banners`
--

INSERT INTO `home_banners` (`id`, `url`, `alt`, `target`, `pos`, `active`) VALUES
(1, 'http://www.lalicorera.com', 'Este es el alt de la imagen 1', '_blank', 10, 0),
(2, 'http://www.google.com/', 'Este es el alt de la imagen 2', '', 8, 0),
(4, 'http://www.lalicorera.com/productos/brandy', 'La licorera lo mejor en BogotÃ¡', '_blank', 7, 0),
(5, 'http://www.lalicorera.com/blog/nosotros', 'Cobertura', '', 7, 1),
(6, 'http://www.lalicorera.com/cocteles', 'Recetas famosas de cocteles', '', 4, 0),
(7, 'http://www.lalicorera.com/blog/nosotros', 'Licores nacionales e importados bogota', '', 3, 0),
(8, 'http://www.lalicorera.com/productos/vodka', 'Vodka importado en bogota', '_blank', 5, 0),
(9, 'http://www.lalicorera.com/productos/ron', 'Ron nacional e importado en bogota', '', 5, 0),
(10, 'http://www.lalicorera.com/productos/whisky', 'Whisky nacional e importado en bogota', '', 6, 0),
(11, 'http://www.lalicorera.com/productos/ron/la-hechicera', 'RON-LA-HECHICERA', '', 5, 0),
(12, 'http://www.lalicorera.com/productos/ginebra/gin-mare', 'Gin-Mare-Bogota', '_blank', 2, 0),
(13, 'http://www.lalicorera.com/productos/especiales/cachaza-51', 'CACHAZA-BOGOTA', '_blank', 6, 0),
(14, 'http://www.lalicorera.com', '31DiciembreLaLicorera', '', 1, 0),
(15, 'http://www.lalicorera.com/productos/ginebra/bulldog', 'http://www.lalicorera.com/productos/ginebra/bulldog', '', 1, 0),
(16, 'http://www.lalicorera.com/productos/ginebra/bulldog', 'GINEBRA-BULLDOG-EN-BOGOTA', '', 1, 0),
(19, 'http://m.me/lalicoreraco', 'Aguardiente a Domicilio', '_blank', 1, 0),
(18, 'https://www.lalicorera.com/productos/whisky/chivas-18-pininfarina', 'Chivas Pininfarina Colombia', '', 2, 0),
(20, 'https://www.lalicorera.com/productos/cerveza/corona-six-pack-cerveza', 'Cerveza Corona a Domicilio', '', 1, 0),
(21, 'https://www.lalicorera.com/productos/cerveza/corona-six-pack-cerveza', 'Cerveza a Domicilio Bogota', '', 3, 0),
(22, 'https://www.lalicorera.com/blog/citadelle-gin-barman-kit', 'Ginebra a Domicilio Licor', '', 2, 0),
(23, 'http://https://www.lalicorera.com', 'LICOR A DOMICILIO', '', 1, 0),
(24, 'https://www.lalicorera.com/productos/black-friday', 'BLACK FRIDAY LICORES', '', 1, 0),
(25, 'https://www.lalicorera.com/productos/tequila/olmeca-reposado', 'Licor a Domicilio', '', 2, 0),
(26, 'https://www.lalicorera.com/productos/whisky/chivas-18-pininfarina', 'Licor a Domicilio Bogota', '', 1, 0),
(27, 'http://https://www.lalicorera.com/productos/whisky/johnnie-walker-red', 'Licor a Domicilio Bogota', '', 1, 0),
(28, 'http://https://www.lalicorera.com/productos/ginebra/beefeater', 'Ginebra Beefeater a Domicilio', '_blank', 1, 0),
(29, 'http://https://www.lalicorera.com/productos/ginebra/beefeater', 'Licor a Domicilio', '', 2, 0),
(30, 'https://www.lalicorera.com/productos/whisky/jameson-whiskey', 'Whisky Jameson', '', 1, 0),
(31, 'https://www.lalicorera.com/productos/whisky/jameson-whiskey', 'Jameson Whisky Colombia', '', 2, 0),
(32, 'https://www.lalicorera.com/productos/promociones/pack-bulldog-fever-tree', 'Licor a Domicilio Bogota', '', 1, 0),
(33, 'https://www.lalicorera.com/productos/whisky/baileys', 'Licor a Domicilio Bogota', '', 2, 0),
(34, 'https://www.lalicorera.com/productos/ginebra/bulldog', 'Licor a Domicilio Bogota', '', 5, 0),
(35, 'https://www.lalicorera.com/productos/promociones/cocktail-week-tanqueray', 'Cocktail Week Bogota Tanqueray', '', 1, 0),
(36, 'http://www.lalicorera.com', 'Licor a Domicilio Bogota', '_blank', 1, 0),
(37, 'https://www.lalicorera.com/productos/promociones/smirnoff-green-apple', 'Licor a Domicilio Bogota', '', 2, 0),
(83, 'https://www.lalicorera.com/productos/whisky/johnnie-walker-red', 'LICOR A DOMICILIO BOGOTA', '', 3, 0),
(84, 'https://hinchaganador.com/', 'Licor a Domicilio Bogota', '', 2, 0),
(40, 'https://www.lalicorera.com/productos/ginebra/bulldog-pack-copas', 'Licor a Domicilio Bogota', '_blank', 3, 0),
(85, 'http://www.lalicorera.com/buscar/paramama', 'Licor a Domicilio Bogota', '', 1, 0),
(42, 'https://www.lalicorera.com/productos/promociones/johnnie-walker-red-promo', 'Licor a Domicilio Bogota', '', 2, 0),
(43, 'https://www.lalicorera.com/productos/ginebra', 'Licor a Domicilio', '', 2, 0),
(44, 'https://www.lalicorera.com/productos/whisky/chivas-extra', 'Domicilio Licores Bogota', '', 1, 0),
(47, 'https://www.lalicorera.com/productos/tequila/olmeca-margarita-mix', 'Licores al Por Mayor', '', 6, 0),
(46, 'https://www.lalicorera.com/productos/whisky/chivas-12-mini-botella-whisky', 'Licores a Domicilio', '', 3, 0),
(48, 'https://www.lalicorera.com/productos/whisky/chivas-12-mini-botella-whisky', 'Licor a Domicilio Bogota', '', 33, 0),
(49, 'https://www.lalicorera.com/productos/whisky/johnnie-walker-red', 'Whisky a Domicilio', '', 1, 0),
(50, 'https://www.lalicorera.com/productos/cerveza/club-colombia-oktoberfest', 'Cerveza a Domicilio', '', 4, 0),
(51, 'https://www.lalicorera.com/productos/whisky/dos-old-parr', 'Whisky Old Parr Colombia', '', 1, 0),
(52, 'https://www.lalicorera.com/productos/whisky/johnnie-walker-black-label', 'Licores a Domicilio Bogota', '', 4, 0),
(53, 'https://www.lalicorera.com/buscar/glenfiddich', 'Whisky a Domicilio', '', 1, 0),
(54, 'https://www.lalicorera.com/buscar/glenfiddich', 'Regalos Para Navidad', '', 3, 0),
(56, 'https://www.lalicorera.com/productos/whisky/chivas-12-mini-botella-whisky', 'Whisky Chivas 12 a Domicilio', '', 1, 0),
(57, 'https://www.lalicorera.com/productos/vodka/absolut-sequin', 'Absolut-Sequin-Domicilio', '', 5, 0),
(58, 'https://www.lalicorera.com/productos/black-friday', 'Licor a Domicilio', '_blank', 4, 0),
(59, 'https://www.lalicorera.com/productos/black-friday/buchanans-18-lamy', 'Black Friday Licor Bogota Colombia', '', 1, 0),
(60, 'https://www.lalicorera.com/productos/black-friday/johnnie-walker-red-promo', 'Black Friday Licor Bogota Colombia', '', 4, 0),
(61, 'https://www.lalicorera.com/productos/black-friday/tanqueray-precio-especial', 'Black Friday Licor Bogota Colombia', '', 4, 0),
(62, 'https://www.lalicorera.com/productos/black-friday/buchanans-black-friday', 'Black Friday Licor Bogota Colombia', '', 4, 0),
(64, 'https://www.lalicorera.com/productos/black-friday', 'Licor a Domicilio', '', 1, 0),
(65, 'https://www.lalicorera.com/productos/black-friday/jameson-promo-regalo', 'Jameson Whiskey', '', 1, 0),
(66, 'https://www.lalicorera.com/productos/whisky/chivas-18-anos', 'Licor a Domicilio', '', 3, 0),
(67, 'https://www.lalicorera.com/buscar/Johnnie%2BWalker', 'Whisky a Domicilio', '', 1, 0),
(70, 'https://www.lalicorera.com/buscar/scotch', 'LICOR A DOMICILIO', '', 1, 0),
(71, 'https://www.lalicorera.com/productos/whisky/old-parr', 'Licor a Domicilio Bogota', '', 2, 0),
(72, 'https://www.lalicorera.com/buscar/Coleccion_Maltas', 'Licor a Domicilio Bogota', '', 3, 0),
(73, 'https://www.lalicorera.com/buscar/diamujer', 'LICOR A DOMICILIO', '', 1, 0),
(74, 'https://www.lalicorera.com/productos/whisky/jameson-whiskey', 'LICOR A DOMICILIO BOGOTA', '', 4, 0),
(75, 'https://www.lalicorera.com/productos/whisky/buchanans-12-johnnie-walker-double-black', 'Licor a Domicilio Bogota', '', 1, 0),
(76, 'http://www.lalicorera.com', 'Licor a Domicilio Bogota', '', 1, 0),
(77, 'https://www.lalicorera.com/buscar/aperol', 'Licor a Domicilio Bogota', '', 4, 0),
(82, 'https://www.lalicorera.com/productos/ginebra/bulldog-pack-jigger', 'Licor a Domicilio Bogota', '', 3, 0),
(79, 'https://www.lalicorera.com/buscar/hechicera', 'Licor a Domicilio Bogota', '', 5, 0),
(80, 'http://www.lalicorera.com/productos/drink-friday', 'Licor a Domicilio Bogota', '', 1, 0),
(81, 'https://www.lalicorera.com/productos/drink-friday', 'LICOR A DOMICILIO', '', 1, 0),
(125, 'https://www.lalicorera.com/productos/vodka/absolut-love-2-cranberry', 'Domicilios Bogota', '', 2, 0),
(86, 'http://www.lalicorera.com/productos/whisky/whisky-old-parr-12-anios-x-2', 'Licor a Domicilio Bogota', '', 2, 0),
(87, 'http://www.lalicorera.com/productos/ginebra/bulldog-pack-jigger', 'Licor a Domicilio Bogota', '', 1, 0),
(89, 'http://www.lalicorera.com/productos/whisky/baileys', 'Licor a Domicilio Bogota', '', 5, 0),
(90, 'http://www.lalicorera.com/productos/ginebra/bulldog-pack-jigger', 'Licor a Domicilio Bogota', '', 3, 0),
(91, 'https://goo.gl/NTNin3', 'LICOR A DOMICILIO BOGOTA', '', 3, 0),
(92, 'http://www.lalicorera.com/buscar/chivas', 'Licor a Domicilio Bogota', '', 1, 0),
(93, 'http://www.lalicorera.com/buscar/red%2Blabel', 'Licor a Domicilio Bogota', '', 3, 0),
(94, 'http://www.lalicorera.com/buscar/julio', 'Licor a Domicilio Bogota', '', 3, 0),
(95, 'http://www.lalicorera.com/productos/whisky/buchanans-18-anos', 'Licor a Domicilio Bogota', '', 4, 0),
(96, 'https://www.lalicorera.com/buscar/old%2Bparr', 'Licor a Domicilio Bogota', '', 4, 0),
(99, 'http://www.lalicorera.com/buscar/chivas', 'Licor a Domicilio Bogota', '', 1, 0),
(97, 'http://www.lalicorera.com/productos/whisky/buchanans-18-anos', 'Licor a Domicilio Bogota', '', 1, 0),
(98, 'http://www.lalicorera.com/buscar/maletin', 'Licor a Domicilio Bogota', '', 2, 0),
(100, 'http://www.lalicorera.com/productos/ron/havana-club-maximo-extra-anejo', 'Licor a Domicilio Bogota', '', 5, 0),
(101, 'https://www.lalicorera.com/cocteles', 'LICOR A DOMICILIO BOGOTA', '', 6, 1),
(102, 'https://goo.gl/5KuJVr', 'LICOR A DOMICILIO BOGOTA', '', 1, 0),
(103, 'https://goo.gl/5KuJVr', 'LICOR A DOMICILIO BOGOTA', '', 1, 0),
(104, 'http://www.lalicorera.com/buscar/nuevosprecios', 'Licor a Domicilio Bogota', '', 2, 0),
(107, 'https://www.lalicorera.com/productos/ginebra/monkey-47', 'LICOR A DOMICILIO BOGOTA', '', 4, 0),
(106, 'http://www.lalicorera.com/productos/whisky/johnnie-walker-black-label', 'Licor a Domicilio Bogota', '', 1, 0),
(108, 'https://www.lalicorera.com/buscar/amoryamistad', 'Domicilios Bogota', '', 1, 0),
(109, 'https://goo.gl/yy6E24', 'LICOR A DOMICILIO BOGOTA', '', 1, 0),
(110, 'https://www.lalicorera.com/buscar/combo_halloween', 'Domicilios Bogota', '', 2, 0),
(112, 'https://www.lalicorera.com/productos/promociones', 'Domicilios Bogota', '', 1, 0),
(113, 'https://www.lalicorera.com/productos/whisky/buchanans-18-anos', 'Domicilios Bogota', '', 3, 1),
(114, '', 'Domicilios Bogota', '_blank', 2, 0),
(117, 'https://www.lalicorera.com/productos/whisky/chivas-extra', 'Domicilios Bogota', '_blank', 1, 0),
(115, 'https://www.lalicorera.com/productos/whisky/chivas-18-anos', 'Domicilios Bogota', '_blank', 1, 0),
(116, 'https://www.lalicorera.com/productos/whisky/glenlivet-founders-reserve', 'Domicilios Bogota', '_blank', 2, 0),
(118, 'https://www.lalicorera.com/productos/whisky/chivas-extra', 'Domicilios Bogota', '_blank', 2, 0),
(119, 'https://www.lalicorera.com/', 'Domicilios Bogota', '', 1, 0),
(122, 'https://www.lalicorera.com/productos/cerveza/budweiser-6-unidades-botella', 'LICOR A DOMICILIO', '', 1, 0),
(123, 'https://www.lalicorera.com/productos/whisky/jameson-whiskey', 'Domicilios Bogota', '', 3, 0),
(126, 'https://www.lalicorera.com/productos/whisky/baileys', 'Domicilios Bogota', '', 1, 0),
(127, 'https://www.lalicorera.com/cocteles', 'LICOR A DOMICILIO', '', 2, 1),
(128, 'http://https://www.lalicorera.com/productos/tequila', 'LICOR A DOMICILIO', '', 1, 0),
(129, 'https://www.lalicorera.com/productos/whisky/white-walker-by-johnnie-walker-edicion-game-of-thrones', 'LICOR A DOMICILIO BOGOTA', '', 3, 1),
(131, 'https://www.lalicorera.com/productos/whisky/white-walker-by-johnnie-walker-edicion-game-of-thrones', 'Domicilios Bogota', '', 1, 1);
